Repository TheoBerlin/GameProject, pull requests merged in 2019-03, with the labels that each got.

#122 Collision fix
  GameProject/Engine/Collision/Collision.cpp
  GameProject/Engine/Collision/Collision.h
  GameProject/Engine/Entity/Entity.h
Labels: fix, optimization

#124 Collision OBB
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/AssetManagement/ModelLoader.h
  GameProject/Engine/Collision/CollisionConfig.h
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Engine/Collision/CollisionHandler.h
  GameProject/Engine/Collision/CollisionInfo.h
  GameProject/Engine/Collision/CollisionRenderer.cpp
  GameProject/Engine/Collision/CollisionRenderer.h
  GameProject/Engine/Collision/VarientMap.h
  GameProject/Engine/Components/MovingTargetCollision.cpp
  GameProject/Engine/Components/PlayerCollision.cpp
  GameProject/Engine/Config.h
  GameProject/Engine/Rendering/GLAbstraction/IndexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/IndexBuffer.h
  GameProject/Game/Assets/Test.fbx
  GameProject/Game/Assets/Test2.fbx
  GameProject/Game/Assets/Test2_1.png
  GameProject/Game/Assets/Test2_2.png
  GameProject/Game/Assets/droneTarget.fbx
  GameProject/Game/Assets/droneTarget2.fbx
  GameProject/Game/Assets/floor.fbx
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/PauseState.h
  GameProject/GameProject.vcxproj
  GameProject/Utils/Utils.cpp
  GameProject/Utils/Utils.h
Labels: Collision, engine

#118 Smoothen arrow replays
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/States/GameState.cpp
  GameProject/imgui.ini
Labels: fix, gameplay

#121 Score
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/GUI/ScrollPanel/List.cpp
  GameProject/Engine/GUI/ScrollPanel/ScrollPanel.cpp
  GameProject/Engine/GUI/ScrollPanel/ScrollPanel.h
  GameProject/Game/Assets/fonts/aldo/aldo.ttf
  GameProject/Game/Assets/logo.png
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.h
  GameProject/Game/GameLogic/ScoreManager.cpp
  GameProject/Game/GameLogic/ScoreManager.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
  GameProject/Game/Level/Level.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelParser.h
  GameProject/Game/Level/level.json
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/MenuState.h
  GameProject/Game/States/PauseState.cpp
  GameProject/GameProject.vcxproj
Labels: GUI, gameplay

#119 Rewind / fast forward replays
  GameProject/Engine/Entity/EntityManager.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.h
  GameProject/Game/GameLogic/ReplaySystem.cpp
  GameProject/Game/GameLogic/ReplaySystem.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/MenuState.h
Labels: gameplay

#125 Fix collision keypoints overwriting each other
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
Labels: fix, gameplay

#132 Separated the transform of the model when in guidingPhase.
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Game/Components/PathTreader.cpp
  GameProject/Game/Components/PathTreader.h
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
Labels: Collision, gameplay

#133 Remove getRotation and fix getYawPitchRoll
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Game/Level/LevelStructure.cpp
Labels: engine, fix

#128 Retry level and move cursor locks to phases
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/GameLogic/ScoreManager.cpp
  GameProject/Game/GameLogic/ScoreManager.h
Labels: GUI, gameplay

#126 Fix collision replay timings and timebar length
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/ReplaySystem.cpp
Labels: fix, gameplay

#130 Exit level
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Game/GameLogic/GameEvents.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/ScoreManager.cpp
  GameProject/Game/GameLogic/ScoreManager.h
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/Game/States/PauseState.cpp
Labels: GUI, gameplay

#136 Camera Drift
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/Phase.cpp
Labels: gameplay

#138 Fix camera blacking out during guiding
  GameProject/Game/Components/ArrowGuider.cpp
Labels: fix, gameplay

#135 Fixed memory issue with replay bar
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
Labels: fix, optimization

#137 Adjust Arrow Settings
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp
  GameProject/Game/Assets/Arrow.fbx
  GameProject/Game/Assets/Arrow.png
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/AimPhase.h
  GameProject/Game/GameLogic/Phases/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/Level/level.json
Labels: gameplay

#142 GUI Fixes
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Button.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/GameLogic/ScoreManager.cpp
Labels: GUI, fix

#143 Fix Transform::resetRoll
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Game/Components/RollNullifier.cpp
Labels: engine, fix

#144 Looping Moving Targets
  GameProject/Game/Components/PathTreader.cpp
  GameProject/Game/Components/PathTreader.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/Level/level.json
Labels: gameplay

#141 Remove double to float truncation
  GameProject/Game/Components/ArrowGuider.cpp
Labels: fix

#146 Fix/warnings
  GameProject/Engine/Particle/ParticleEmitter.cpp
  GameProject/Engine/Particle/ParticleEmitter.h
  GameProject/Engine/Particle/ParticleManager.cpp
Labels: fix

#147 Score menu displayable before ending replay
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
Labels: gameplay

#151 Switchable Third Person Camera
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Engine/Components/Component.cpp
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/Components/ThirdPersonController.cpp
  GameProject/Game/Components/ThirdPersonController.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/Level/Level.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/Levels/Level 1.json
  GameProject/Game/Level/Levels/Level 2.json
  GameProject/Game/Level/Levels/level.json
  GameProject/Game/Level/Levels/newLevel.json
  GameProject/Game/Level/Levels/newLevel2.json
  GameProject/GameProject.vcxproj
Labels: gameplay

#157 Collision free transitions
  GameProject/Game/Components/CameraTransition.cpp
  GameProject/Game/Components/CameraTransition.h
  GameProject/Game/Components/PathTreader.cpp
  GameProject/Game/Components/PathTreader.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phases/Phase.cpp
  GameProject/Game/GameLogic/Phases/Phase.h
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/Level/LevelStructure.cpp
  GameProject/Game/Level/LevelStructure.h
Labels: gameplay

#158 GUI guiding targets
  GameProject/Engine/GUI/GUI.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Game/Assets/droneIcon.png
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.h
  GameProject/Game/GameLogic/ScoreManager.cpp
Labels: GUI

#160 Move camera drift to separate component
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/Components/CameraDrift.cpp
  GameProject/Game/Components/CameraDrift.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/GameProject.vcxproj
Labels: fix, gameplay

#150 Cleaned pipeline from old rendering
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/AimPhase.h
Labels: optimization

#167 Removed lowercase i
  GameProject/Game/Level/LevelParser.cpp
Labels: optimization

#154 Roof
  GameProject/Engine/Rendering/GLAbstraction/Shader.cpp
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Shaders/InfinityPlanePrePassShader.frag
  GameProject/Engine/Rendering/Shaders/InfinityPlaneShader.frag
  GameProject/Engine/Rendering/Shaders/RoofShader.frag
  GameProject/Engine/Rendering/Shaders/RoofShader.vert
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/RoofShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/RoofShader.h
  GameProject/Game/Level/LevelStructure.cpp
  GameProject/Game/Level/LevelStructure.h
  GameProject/GameProject.vcxproj
Labels: engine, gameplay, rendering

#169 Replay camera transitions
  GameProject/Game/Components/CameraDrift.cpp
  GameProject/Game/Components/CameraDrift.h
  GameProject/Game/Components/CameraTransition.cpp
  GameProject/Game/Components/CameraTransition.h
  GameProject/Game/Components/PathTreader.cpp
  GameProject/Game/Components/PathTreader.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/Phase.cpp
  GameProject/Game/GameLogic/Phases/Phase.h
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
Labels: gameplay

#172 Glow Effect and Post Processing
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Engine/Components/Component.cpp
  GameProject/Engine/Particle/Particle.frag
  GameProject/Engine/Rendering/GLAbstraction/RenderingResources.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Engine/Rendering/Shaders/BlurFilter.frag
  GameProject/Engine/Rendering/Shaders/CombineShader.frag
  GameProject/Engine/Rendering/Shaders/EntityShader.frag
  GameProject/Engine/Rendering/Shaders/EntityShader.vert
  GameProject/Engine/Rendering/Shaders/EntityShaderInstanced.frag
  GameProject/Engine/Rendering/Shaders/PostProcessFrag.frag
  GameProject/Engine/Rendering/Shaders/RewindShader.frag
  GameProject/Engine/Rendering/Shaders/RewindShader.vert
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/RewindShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/RewindShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/TrailShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/TrailShader.h
  GameProject/Engine/Rendering/Shaders/TrailEffect.frag
  GameProject/Engine/Rendering/Shaders/TrailEffect.vert
  GameProject/Engine/Rendering/Shaders/ZPrepassFrag.frag
  GameProject/Engine/Rendering/Shaders/droneShaderInstanced.frag
  GameProject/Engine/Rendering/Shaders/droneShaderInstanced.vert
  GameProject/Game/Assets/Arrow.fbx
  GameProject/Game/Assets/droneTarget.fbx
  GameProject/Game/Assets/droneTex.png
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/Components/CameraTransition.cpp
  GameProject/Game/Components/ComponentResources.h
  GameProject/Game/Components/TrailEmitter.cpp
  GameProject/Game/Components/TrailEmitter.h
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.h
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/States/GameState.cpp
  GameProject/Game/assets/textures/RewindEffect.png
  GameProject/GameProject.vcxproj
Labels: engine, rendering

#164 GUI show function buttons
  GameProject/Engine/GUI/GUIColors.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/Rendering/GUIRenderer.cpp
  GameProject/Game/Assets/buttons/1.png
  GameProject/Game/Assets/buttons/2.png
  GameProject/Game/Assets/buttons/3.png
  GameProject/Game/Assets/buttons/a.png
  GameProject/Game/Assets/buttons/ctrl.png
  GameProject/Game/Assets/buttons/d.png
  GameProject/Game/Assets/buttons/f1.png
  GameProject/Game/Assets/buttons/mouse1.png
  GameProject/Game/Assets/buttons/mouse2.png
  GameProject/Game/Assets/buttons/mouse3.png
  GameProject/Game/Assets/buttons/s.png
  GameProject/Game/Assets/buttons/shift.png
  GameProject/Game/Assets/buttons/space.png
  GameProject/Game/Assets/buttons/w.png
  GameProject/Game/Assets/buttons/wasd.png
  GameProject/Game/Assets/buttons/wasdMini.png
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/HelpGUI.cpp
  GameProject/Game/HelpGUI.h
  GameProject/Game/Level/Level.h
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/Game/States/MenuState.cpp
  GameProject/GameProject.vcxproj
Labels: GUI

#159 Lighting update (Now pointlights can be updated during runtime)
  GameProject/Engine/Rendering/Lighting/PointLight.cpp
  GameProject/Engine/Rendering/Lighting/PointLight.h
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
Labels: engine, rendering

#178 Fixed panel not getting a texture at start
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/Level/Levels/Level 1.json
Labels: fix

#180 Fixed lowercase names, also fixed mismatched warnings
  GameProject/Game/Level/LevelParser.cpp
Labels: fix

#168 Shadow projection now match the level.
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/AssetManagement/TextureManager.cpp
  GameProject/Engine/AssetManagement/TextureManager.h
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Engine/Collision/CollisionHandler.h
  GameProject/Engine/Config.h
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/Display.h
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.h
  GameProject/Engine/Rendering/GLAbstraction/IndexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.h
  GameProject/Engine/Rendering/Lighting/DirectionalLight.h
  GameProject/Engine/Rendering/Lighting/LightManager.cpp
  GameProject/Engine/Rendering/Lighting/LightManager.h
  GameProject/Engine/Rendering/LineRenderer.cpp
  GameProject/Engine/Rendering/LineRenderer.h
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Shaders/EntityShaderInstanced.frag
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelStructure.cpp
  GameProject/Game/Level/LevelStructure.h
  GameProject/Game/Level/Levels/Level 1.json
  GameProject/Game/Level/Levels/Level 2.json
  GameProject/Game/Level/Levels/level.json
  GameProject/Game/States/GameState.cpp
  GameProject/GameProject.vcxproj
  GameProject/Utils/Settings.cpp
  GameProject/Utils/Settings.h
  GameProject/Utils/Settings.json
  GameProject/Utils/Utils.cpp
  GameProject/Utils/Utils.h
Labels: engine

#193 Moving target ghost
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Shaders/DroneGhostShaderInstanced.frag
  GameProject/Engine/Rendering/Shaders/DroneGhostShaderInstanced.vert
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneGhostShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneGhostShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h
  GameProject/Game/Assets/droneTarget2.fbx
  GameProject/Game/Assets/droneTargetMoving.fbx
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/Level/LevelParser.cpp
  GameProject/GameProject.vcxproj
Labels: gameplay

#188 Player collisions stop spamming logs
  GameProject/Engine/Components/PlayerCollision.cpp
Labels: fix

#177 Pausable replays
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Engine/Entity/EntityManager.cpp
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Game/Assets/buttons/playPause.png
  GameProject/Game/Components/Explosion.cpp
  GameProject/Game/GameLogic/Phases/AimPhase.cpp
  GameProject/Game/GameLogic/Phases/GuidingPhase.cpp
  GameProject/Game/GameLogic/Phases/Phase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/GameLogic/ReplaySystem.cpp
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/States/GameState.cpp
  GameProject/Game/components/DeathAnimation.cpp
  GameProject/Game/components/DeathAnimation.h
Labels: gameplay

#187 Lower pitch when pausing the game
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Sound/Sound.cpp
  GameProject/Engine/Sound/Sound.h
  GameProject/Engine/Sound/SoundManager.cpp
  GameProject/Engine/Sound/SoundManager.h
  GameProject/Game/Assets/buttons/slowMotion.png
  GameProject/Game/Components/Explosion.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
  GameProject/Game/GameLogic/Phases/ReplayPhase.h
  GameProject/Game/GameLogic/ReplaySystem.cpp
  GameProject/Utils/Settings.cpp
Labels: gameplay

#200 Can now enable and disable logging
  GameProject/Engine/Config.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelParser.h
  GameProject/Utils/Logger.h
  GameProject/main.cpp
Labels: engine

#209 Fix vector addition causing gl errors
  GameProject/Engine/Rendering/Shaders/DroneGhostShaderInstanced.frag
Labels: fix

#213 Fixes like loading during runtime and misc
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Game/Components/PathVisualizer.cpp
  GameProject/Game/Components/TrailEmitter.cpp
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelParser.h
  GameProject/Game/States/EditorState.cpp
Labels: fix
