Repository TheoBerlin/GameProject, pull requests merged in 2019-02, with the labels that each got.

#37 Couple mesh and buffers
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/AssetManagement/Model.h
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
Labels: rendering

#41 Controllable arrow
  GameProject/Engine/Components/Component.cpp
  GameProject/Engine/Components/Component.h
  GameProject/Engine/Events/Events.h
  GameProject/Game/components/ArrowGuider.cpp
  GameProject/Game/components/ArrowGuider.h
  GameProject/GameProject.vcxproj
  GameProject/Tests/Events_test.cpp
  GameProject/Tests/Tests.vcxproj
  GameProject/Tests/arrow_test.cpp
  GameProject/Tests/main_test.cpp
Labels: gameplay

#42 Camera and FreeMove
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/AssetManagement/Model.h
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/AssetManagement/ModelLoader.h
  GameProject/Engine/AssetManagement/TextureManager.cpp
  GameProject/Engine/AssetManagement/TextureManager.h
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Engine/Components/Component.cpp
  GameProject/Engine/Components/Component.h
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Engine/Config.h
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/EntityManager.cpp
  GameProject/Engine/Entity/EntityMatrix.cpp
  GameProject/Engine/Entity/EntityMatrix.h
  GameProject/Engine/Events/EventBus.h
  GameProject/Engine/Events/Events.h
  GameProject/Engine/InputHandler.cpp
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/Display.h
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.h
  GameProject/Engine/Rendering/GLAbstraction/IndexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/IndexBuffer.h
  GameProject/Engine/Rendering/GLAbstraction/RenderingResources.h
  GameProject/Engine/Rendering/GLAbstraction/Shader.cpp
  GameProject/Engine/Rendering/GLAbstraction/Shader.h
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.h
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Engine/Rendering/Shaders/EntityShader.frag
  GameProject/Engine/Rendering/Shaders/EntityShader.vert
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/TestState.cpp
  GameProject/Game/States/TestState.h
  GameProject/Game/assets/Target.fbx
  GameProject/Game/assets/TargetDiffuse.png
  GameProject/GameProject.vcxproj
  GameProject/main.cpp
  include/assimp/material.inl
Labels: engine, rendering

#45 Fix compiling error
  GameProject/Tests/AssetLoading_test.cpp
  GameProject/Tests/Tests.vcxproj
Labels: fix

#44 Rendering
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/AssetManagement/TextureManager.cpp
  GameProject/Engine/AssetManagement/TextureManager.h
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.h
  GameProject/Engine/Rendering/GLAbstraction/RenderingResources.h
  GameProject/Engine/Rendering/GLAbstraction/Shader.cpp
  GameProject/Engine/Rendering/GLAbstraction/Shader.h
  GameProject/Engine/Rendering/GLAbstraction/Texture.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Game/States/TestState.cpp
  GameProject/GameProject.vcxproj
Labels: engine, rendering

#51 Matrix transformation
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/ModelLoader.h
  GameProject/Engine/AssetManagement/TextureManager.h
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/EntityMatrix.cpp
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Engine/Level/LevelParser.cpp
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Game/States/TestState.cpp
  GameProject/Game/States/TestState.h
  GameProject/Game/components/ArrowGuider.cpp
  GameProject/Game/components/ArrowGuider.h
  GameProject/GameProject.vcxproj
  GameProject/Tests/AssetLoading_test.cpp
  GameProject/Tests/Tests.vcxproj
  GameProject/Tests/arrow_test.cpp
Labels: engine

#50 Tiny freemove optimization
  GameProject/Engine/Components/FreeMove.cpp
Labels: engine

#54 Fix/fixed dt
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/IGame.cpp
  GameProject/Utils/Timer.cpp
Labels: fix

#47 Arrow Guider
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Engine/Components/Component.cpp
  GameProject/Engine/Config.h
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Game/components/ArrowGuider.cpp
  GameProject/Game/components/ArrowGuider.h
  GameProject/Tests/arrow_test.cpp
Labels: gameplay

#55 Matrix Transformation
  GameProject/Engine/Entity/EntityMatrix.cpp
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/GameProject.vcxproj
Labels: engine, fix

#73 Moving targets
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Engine/Level/LevelParser.cpp
  GameProject/Engine/Level/LevelParser.h
  GameProject/Engine/Level/level.json
  GameProject/Game/Assets/droneTarget.fbx
  GameProject/Game/Components/PathTreader.cpp
  GameProject/Game/Components/RollNullifier.cpp
  GameProject/Game/Components/RollNullifier.h
  GameProject/GameProject.vcxproj
Labels: gameplay

#74 Gui
  GameProject/Engine/GUI/Font.cpp
  GameProject/Engine/GUI/Font.h
  GameProject/Engine/GUI/FontManager.cpp
  GameProject/Engine/GUI/FontManager.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/GUI/Text.cpp
  GameProject/Engine/GUI/Text.h
  GameProject/Engine/IGame.cpp
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/Display.h
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.h
  GameProject/Engine/Rendering/GLAbstraction/GLFormats.h
  GameProject/Engine/Rendering/GLAbstraction/Shader.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.h
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.h
  GameProject/Engine/Rendering/GUIRenderer.cpp
  GameProject/Engine/Rendering/GUIRenderer.h
  GameProject/Engine/Rendering/Shaders/Font.frag
  GameProject/Engine/Rendering/Shaders/Font.vert
  GameProject/Engine/Rendering/Shaders/PanelShader.frag
  GameProject/Engine/Rendering/Shaders/PanelShader.vert
  GameProject/Engine/Rendering/Shaders/TexShader.frag
  GameProject/Engine/Rendering/Shaders/TexShader.vert
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/MenuState.h
  GameProject/Game/assets/fonts/SegoeScript/segoesc.ttf
  GameProject/Game/assets/fonts/SegoeScript/segoescb.ttf
  GameProject/Game/assets/fonts/arial/arial.ttf
  GameProject/Game/assets/fonts/arial/arialbd.ttf
  GameProject/Game/assets/fonts/arial/arialbi.ttf
  GameProject/Game/assets/fonts/arial/ariali.ttf
  GameProject/Game/assets/fonts/arial/ariblk.ttf
  GameProject/Game/assets/fonts/times/times.ttf
  GameProject/Game/assets/fonts/times/timesbd.ttf
  GameProject/Game/assets/fonts/times/timesbi.ttf
  GameProject/Game/assets/fonts/times/timesi.ttf
  GameProject/GameProject.vcxproj
Labels: GUI, engine, rendering

#79 Renderer
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/AssetManagement/Model.h
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/AssetManagement/ModelLoader.h
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Engine/IGame.cpp
  GameProject/Engine/IGame.h
  GameProject/Engine/Rendering/GLAbstraction/RenderingResources.h
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.h
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/VertexBuffer.h
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Engine/Rendering/Shaders/EntityShaderInstanced.frag
  GameProject/Engine/Rendering/Shaders/EntityShaderInstanced.vert
  GameProject/Engine/States/State.h
  GameProject/Engine/States/StateManager.cpp
  GameProject/Engine/States/StateManager.h
  GameProject/Game/Assets/droneTarget.fbx
  GameProject/Game/Assets/droneTex.png
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Game.cpp
  GameProject/Game/Game.h
  GameProject/Game/GameLogic.cpp
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/MenuState.h
  GameProject/Game/States/TestState.cpp
  GameProject/Game/States/TestState.h
  GameProject/Utils/Settings.json
Labels: engine, rendering

#77 Reset level
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Level/Level.cpp
  GameProject/Engine/Level/Level.h
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
  GameProject/Game/Level/Level.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelParser.h
  GameProject/Game/Level/level.json
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/GameProject.vcxproj
Labels: gameplay

#87 Phase classes
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/Entity/Entity.h
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Engine/Events/Events.h
  GameProject/Engine/Events/memberFunctionHandler.h
  GameProject/Game/Components/PathVisualizer.cpp
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/GameLogic/OverviewPhase.h
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.h
  GameProject/GameProject.vcxproj
Labels: gameplay

#84 Limit pitch in camera components
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
Labels: fix, gameplay

#83 Overview camera
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/Components/OversightController.h
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/GameProject.vcxproj
Labels: gameplay

#89 Bugfix
  GameProject/Engine/AssetManagement/TextureManager.cpp
  GameProject/Engine/AssetManagement/TextureManager.h
  GameProject/Engine/Rendering/Display.h
  GameProject/Engine/Rendering/GLAbstraction/Texture.cpp
  GameProject/Engine/Rendering/GLAbstraction/Texture.h
  GameProject/Utils/Logger.cpp
  GameProject/Utils/Logger.h
  GameProject/main.cpp
Labels: fix

#88 Added GL error callback and fixed unnecessary binds to framebuffer.
  GameProject/Engine/Config.h
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/Display.h
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.h
  GameProject/Game/States/MenuState.cpp
  GameProject/Utils/Logger.cpp
  GameProject/Utils/Logger.h
Labels: engine

#91 InputHandler optimization and added functionality
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Engine/Events/Events.h
  GameProject/Engine/InputHandler.cpp
  GameProject/Engine/InputHandler.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Utils/Settings.json
Labels: optimization

#93 Fix/eventbus
  GameProject/Engine/Events/EventBus.h
Labels: fix

#85 Camera Transitions
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Engine/Events/EventBus.h
  GameProject/Engine/Events/Events.h
  GameProject/Game/Components/CameraTransition.cpp
  GameProject/Game/Components/CameraTransition.h
  GameProject/Game/GameLogic.cpp
  GameProject/Game/GameLogic.h
  GameProject/Game/GameLogic/AimPhase.cpp
  GameProject/Game/GameLogic/AimPhase.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/GameLogic/OverviewPhase.h
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.h
  GameProject/Game/Level/Level.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/LevelParser.h
  GameProject/Game/Level/level.json
  GameProject/Game/States/GameState.cpp
  GameProject/GameProject.vcxproj
Labels: gameplay

#95 Button improvement and added removePanel and removeAllPanels to GUI.
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Events/Events.h
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Button.h
  GameProject/Engine/GUI/GUI.cpp
  GameProject/Engine/GUI/GUI.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/Rendering/GLAbstraction/Texture.cpp
  GameProject/Engine/Sound/Sound.cpp
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/States/MenuState.cpp
  GameProject/Utils/Logger.cpp
  GameProject/Utils/Logger.h
Labels: GUI, engine

#96 Gui
  GameProject/Engine/Events/EventBus.h
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/Rendering/GUIRenderer.cpp
Labels: GUI, fix

#97 Fixed button still being active.
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Button.h
  GameProject/Engine/GUI/GUI.cpp
  GameProject/Engine/GUI/GUI.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/States/StateManager.cpp
  GameProject/Game/States/MenuState.cpp
Labels: fix

#98 Fix EventBus not unsubscribing handlers
  GameProject/Engine/Events/EventBus.h
Labels: fix

#101 Removed unnecessary includes of logger.h
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/PlayerCollision.cpp
  GameProject/Engine/InputHandler.cpp
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp
  GameProject/Engine/Rendering/GLAbstraction/Shader.cpp
  GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp
  GameProject/Engine/Rendering/GUIRenderer.cpp
  GameProject/Engine/Sound/Sound.cpp
  GameProject/Engine/Sound/SoundContext.cpp
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/States/MenuState.cpp
  GameProject/Utils/Settings.cpp
Labels: optimization

#99 Added mouseScrollEvent
  GameProject/Engine/Events/Events.h
  GameProject/Engine/InputHandler.cpp
  GameProject/Engine/InputHandler.h
Labels: engine

#100 Removed warnings for project and rp3d
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Engine/Collision/CollisionHandler.h
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/libs/reactphysics3d.pdb
  include/reactphysics3d/collision/shapes/HeightFieldShape.h
Labels: fix, optimization

#104 Target hover
  GameProject/Game/Components/Hover.cpp
  GameProject/Game/Components/Hover.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
  GameProject/GameProject.vcxproj
Labels: gameplay

#103 Collision components rework
  GameProject/Engine/Components/CollisionComponent.cpp
  GameProject/Engine/Components/CollisionComponent.h
  GameProject/Engine/Components/MovingTargetCollision.cpp
  GameProject/Engine/Components/MovingTargetCollision.h
  GameProject/Engine/Components/PlayerCollision.cpp
  GameProject/Engine/Components/PlayerCollision.h
  GameProject/Engine/Components/StaticTargetCollision.cpp
  GameProject/Engine/Components/StaticTargetCollision.h
  GameProject/Engine/Components/TargetCollision.cpp
  GameProject/Engine/Components/TargetCollision.h
  GameProject/Game/GameLogic/AimPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/Level/LevelParser.cpp
  GameProject/GameProject.vcxproj
Labels: engine

#102 Remove transition snapping
  .gitignore
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/FreeMove.cpp
  GameProject/Engine/Components/FreeMove.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/Components/CameraTransition.cpp
  GameProject/Game/Components/CameraTransition.h
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/Components/OversightController.h
  GameProject/Game/GameLogic/AimPhase.cpp
  GameProject/Game/GameLogic/AimPhase.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/Level/Level.h
  GameProject/Game/Level/LevelParser.cpp
  GameProject/Game/Level/level.json
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/TestState.cpp
  GameProject/Game/States/TestState.h
  GameProject/GameProject.vcxproj
Labels: fix, gameplay

#107 Replay system
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplaySystem.cpp
  GameProject/Game/GameLogic/ReplaySystem.h
  GameProject/Game/Level/Level.h
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/GameProject.vcxproj
Labels: gameplay

#108 Collisioncoloring
  GameProject/Engine/AssetManagement/Mesh.cpp
  GameProject/Engine/AssetManagement/Mesh.h
  GameProject/Engine/AssetManagement/Model.cpp
  GameProject/Engine/AssetManagement/Model.h
  GameProject/Engine/Components/StaticTargetCollision.cpp
  GameProject/Engine/Rendering/GLAbstraction/Shader.h
  GameProject/Engine/Rendering/GLAbstraction/VertexArray.cpp
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h
  GameProject/Engine/Rendering/Shaders/droneShaderInstanced.frag
  GameProject/Engine/Rendering/Shaders/droneShaderInstanced.vert
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/States/GameState.cpp
  GameProject/Game/assets/textures/noise.jpg
  GameProject/GameProject.vcxproj
Labels: gameplay, rendering

#113 Collision component optimization
  GameProject/Engine/Collision/CollisionHandler.cpp
  GameProject/Engine/Collision/CollisionHandler.h
  GameProject/Engine/Collision/CollisionInfo.h
  GameProject/Engine/Components/MovingTargetCollision.cpp
  GameProject/Engine/Components/MovingTargetCollision.h
  GameProject/Engine/Components/PlayerCollision.cpp
  GameProject/Engine/Components/StaticTargetCollision.cpp
  GameProject/Engine/Components/StaticTargetCollision.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/GameLogic/TargetManager.h
  GameProject/GameProject.vcxproj
Labels: fix, optimization

#110 Collision keypoints
  GameProject/Engine/Events/EventBus.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/Components/ComponentResources.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
Labels: gameplay

#105 Track flighttime in guidingphase
  GameProject/Engine/Events/EventBus.h
  GameProject/Game/Components/ArrowGuider.cpp
  GameProject/Game/Components/ArrowGuider.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
Labels: fix, gameplay

#117 Fix oversight controller bumping
  GameProject/Game/Components/OversightController.cpp
  GameProject/Game/Components/OversightController.h
Labels: fix, gameplay

#116 Fix twitching when starting cam transition
  GameProject/Engine/Components/Camera.cpp
  GameProject/Engine/Components/Camera.h
  GameProject/Game/GameLogic/Phase.cpp
Labels: fix, gameplay

#114 Randomized hover starting time
  GameProject/Engine/Entity/Transform.cpp
  GameProject/Engine/Entity/Transform.h
  GameProject/Game/Components/Hover.cpp
  GameProject/Game/Components/Hover.h
Labels: gameplay

#120 Change Levels and Pause
  GameProject/Engine/AssetManagement/ModelLoader.cpp
  GameProject/Engine/Entity/Entity.cpp
  GameProject/Engine/GUI/Button.cpp
  GameProject/Engine/GUI/Button.h
  GameProject/Engine/GUI/GUI.cpp
  GameProject/Engine/GUI/GUI.h
  GameProject/Engine/GUI/Panel.cpp
  GameProject/Engine/GUI/Panel.h
  GameProject/Engine/GUI/ScrollPanel/List.cpp
  GameProject/Engine/GUI/ScrollPanel/List.h
  GameProject/Engine/GUI/ScrollPanel/ScrollBar.cpp
  GameProject/Engine/GUI/ScrollPanel/ScrollBar.h
  GameProject/Engine/GUI/ScrollPanel/ScrollPanel.cpp
  GameProject/Engine/GUI/ScrollPanel/ScrollPanel.h
  GameProject/Engine/Rendering/Display.cpp
  GameProject/Engine/Rendering/Pipeline.cpp
  GameProject/Engine/Rendering/Pipeline.h
  GameProject/Engine/Rendering/Renderer.cpp
  GameProject/Engine/Rendering/Renderer.h
  GameProject/Engine/Rendering/Shaders/BlurFilter.frag
  GameProject/Engine/Rendering/Shaders/BlurFilter.vert
  GameProject/Engine/Rendering/Shaders/PostProcessFrag.frag
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/DroneShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/BlurShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/BlurShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/PostProcessShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/PostProcessShader.h
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/QuadShader.cpp
  GameProject/Engine/Rendering/Shaders/ShaderShells/PostProcess/QuadShader.h
  GameProject/Engine/States/State.cpp
  GameProject/Engine/States/State.h
  GameProject/Engine/States/StateManager.cpp
  GameProject/Engine/States/StateManager.h
  GameProject/Game/Assets/Cube.fbx
  GameProject/Game/Assets/Cube.png
  GameProject/Game/GameLogic/AimPhase.cpp
  GameProject/Game/GameLogic/AimPhase.h
  GameProject/Game/GameLogic/GuidingPhase.cpp
  GameProject/Game/GameLogic/GuidingPhase.h
  GameProject/Game/GameLogic/OverviewPhase.cpp
  GameProject/Game/GameLogic/OverviewPhase.h
  GameProject/Game/GameLogic/Phase.cpp
  GameProject/Game/GameLogic/Phase.h
  GameProject/Game/GameLogic/ReplayPhase.cpp
  GameProject/Game/GameLogic/ReplayPhase.h
  GameProject/Game/GameLogic/TargetManager.cpp
  GameProject/Game/Level/newLevel.json
  GameProject/Game/Level/newLevel2.json
  GameProject/Game/States/GameState.cpp
  GameProject/Game/States/GameState.h
  GameProject/Game/States/MenuState.cpp
  GameProject/Game/States/MenuState.h
  GameProject/Game/States/PauseState.cpp
  GameProject/Game/States/PauseState.h
  GameProject/GameProject.vcxproj
  GameProject/main.cpp
Labels: GUI, engine, fix, rendering
